name: GitHub Actions Flask-HelloWorld

env:
    REPO_NAME: ${{ github.event.repository.name }}

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ${{ github.workspace }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/docker-login@v2
              with:
                    login-server: ${{ secrets.ACR_NAME }}
                    username: ${{ secrets.REGISTRY_USERNAME }}
                    password: ${{ secrets.REGISTRY_PASSWORD }}
            - run: |
                docker build . -t ${{ secrets.ACR_NAME }}/$REPO_NAME:{${{ github.sha }}}
                docker push ${{ secrets.ACR_NAME }}/$REPO_NAME:{${{ github.sha }}}